services:
    jwt_token_authentificator:
        class: AuthenticationBundle\Security\JwtTokenAuthenticator
        autowire: true

    api.response_factory:
         class: AuthenticationBundle\Api\ResponseFactory

    api_exception_subscriber:
        class: AuthenticationBundle\EventListener\ApiExceptionSubscriber
        arguments: ['%kernel.debug%', '@api.response_factory']
        tags:
            - { name: kernel.event_subscriber }