#
# First versions of api.
#
api_v1:
    resource: '@AppBundle/Resources/config/routing/v1.yml'
    prefix: /api/v1

app:
    resource: '@AppBundle/Controller/IndexController.php'
    type: annotation

auth:
    resource: 'routing_security.yml'
    prefix: /security