services:
    user.user_manipulator:
        class: UserBundle\Util\UserManipulator
        arguments:
            - '@fos_user.user_manager'
            - '@event_dispatcher'
            - '@request_stack'

    user.form.registration:
        class: UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: user_registration }